In [247]:
import numpy as np

## Esercizio 1

Scrivere una functione che, dato un intero $n$, costruisce la seguente matrice $n\times n$ (l'esempio seguente è per il caso $n=7$).

$$\begin{pmatrix}
  -2 &1 &0 &0 &0 &0 &0\\
  1& -2&1 &0 & 0 &0 &0\\
  0& 1&-2 &1 & 0 &0 &0\\
  0& 0&1 &-2 & 1 &0 &0\\
  0& 0&0 &1 & -2 &1 &0\\
  0& 0&0 &0 & 1 &-2 &1\\
  0& 0&0 &0 & 0 &1&-2
  \end{pmatrix}$$

In [248]:
# Soluzione con 0 cicli
def es1_sol1(n: int):
    return (
        -2. * np.eye(n, dtype=int)
        + np.eye(n, k=-1, dtype=int)
        + np.eye(n, k=1, dtype=int)
    )

# Esempio
n = 7
print('Output:\n', es1_sol1(n))

Output:
 [[-2.  1.  0.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.  0.  0.]
 [ 0.  1. -2.  1.  0.  0.  0.]
 [ 0.  0.  1. -2.  1.  0.  0.]
 [ 0.  0.  0.  1. -2.  1.  0.]
 [ 0.  0.  0.  0.  1. -2.  1.]
 [ 0.  0.  0.  0.  0.  1. -2.]]


## Esercizio 2

Scrivere una functione che riceve in ingresso un vettore di valori binari di $n$ componenti
e una matrice $A$ di dimensione $n\times m$ e restituisce in uscita una matrice $n\times m$ le cui righe coincidono con quelle di $A$ se le componenti del vettore con lo stesso indice sono 1, sono nulle altrimenti  

Esempio ($n=6$)

$$\text{INPUT}:
\begin{pmatrix}1\\
0 \\ 0 \\ 1 \\ 0 \\ 1
\end{pmatrix}, \begin{pmatrix}
a_{11} & a_{12}& a_{13}& ...& a_{1m}\\
a_{21} & a_{22}& a_{23}& ...& a_{2m}\\
a_{31} & a_{32}& a_{33}& ...& a_{3m}\\
a_{41} & a_{42}& a_{43}& ...& a_{4m}\\
a_{51} & a_{52}& a_{53}& ...& a_{5m}\\
a_{61} & a_{62}& a_{63}& ...& a_{6m}
\end{pmatrix}\qquad\text{OUTPUT}:
\begin{pmatrix}
a_{11} & a_{12}& a_{13}& ...& a_{1m}\\
0 & 0& 0& ...& 0\\
0 & 0& 0& ...& 0\\
a_{41} & a_{42}& a_{43}& ...& a_{4m}\\
0 & 0& 0& ...& 0\\
a_{61} & a_{62}& a_{63}& ...& a_{6m}\end{pmatrix}
$$

In [249]:
# Soluzione con 1 ciclo
def es2_sol1(bmap, M_):
    M = M_.copy()
    for i in range(bmap.size):
        if bmap[i]: continue
        M[i,:] = 0
    return M

# Soluzione con 0 cicli (+ efficiente)
def es2_sol2(bmap, M_):
    M = M_.copy()
    # Seleziona le righe dove bmap==0 e azzera
    M[~bmap.astype(bool), :] = 0
    return M

# Esempio
n = 6
M = np.arange(1, n**2 + 1).reshape((n, n))
bmap = np.array([1, 0, 0, 1, 0, 1])

print('Input:\n', M)
print('Output:\n', es2_sol2(bmap, M))

Input:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Output:
 [[ 1  2  3  4  5  6]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [19 20 21 22 23 24]
 [ 0  0  0  0  0  0]
 [31 32 33 34 35 36]]


## Esercizio 3

Scrivere una functione che, dato un intero $n$, restituisce la matrice di Wilkinson di dimensione $n\times n$, definita nel modo seguente

$$ A = \begin{pmatrix}
1 &   & & & & & 1\\
-1& 1 & & & & & 1\\
-1&-1& 1& & & & 1\\
\vdots & & &\ddots & & &\vdots\\
-1& -1 & -1 &        && 1& 1\\
-1& -1&-1 & \cdots & \cdots &-1&1
\end{pmatrix}$$

In [250]:
# Soluzione con somme
def es3_sol1(n: int):
    # Diagonale principale e triangolo inferiore
    M = np.eye(n) + np.tril(-np.ones((n, n)), -1)
    # Ultima colonna
    M[:,n-1] = 1
    return M

# Esempio
n = 7
print('Output:\n', es3_sol1(n))

Output:
 [[ 1.  0.  0.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  0.  0.  1.]
 [-1. -1.  1.  0.  0.  0.  1.]
 [-1. -1. -1.  1.  0.  0.  1.]
 [-1. -1. -1. -1.  1.  0.  1.]
 [-1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1.  1.]]


## Esercizio 4

Scrivere una functione che riceve in input una matrice $A$ di dimensioni $n\times n$ e due interi $u,l$. La function deve costruire un'altra matrice di dimensioni $n\times(u+l+1)$ le cui righe sono costituite, nell'ordine, dalle $u$ diagonali superiori, dalla diagonale principale, dalle $l$ diagonali inferiori di $A$.

Esempio ($n=6$, $u=1$, $l=2$)

$$\text{INPUT:}
\begin{pmatrix}
\color{lightblue}{a_{11}}&a_{12}&a_{13}&a_{14}&a_{15}&a_{16}\\
a_{21}&a_{22}&a_{23}&a_{24}&a_{25}&a_{26}\\
a_{31}&a_{32}&a_{33}&a_{34}&a_{35}&a_{36}\\
a_{41}&a_{42}&a_{43}&a_{44}&a_{45}&a_{46}\\
a_{51}&a_{52}&a_{53}&a_{54}&a_{55}&a_{56}\\
a_{61}&a_{62}&a_{63}&a_{64}&a_{65}&a_{66}
\end{pmatrix}\qquad\text{OUTPUT:}
\begin{pmatrix}
0&a_{12}&a_{23}&a_{34}&a_{45}&a_{56}\\
a_{11}&a_{22}&a_{33}&a_{44}&a_{55}&a_{66}\\
a_{21}&a_{32}&a_{43}&a_{54}&a_{65}&0\\
a_{31}&a_{42}&a_{53}&a_{64}&0&0
\end{pmatrix}
$$

In [251]:
# Soluzione con cicli
def es4_sol1(A, u: int, l: int):
    n = A.shape[0]
    d = u + l + 1
    O = np.zeros((d, n))
    
    # Diagonale principale
    O[u, :] = np.diag(A, 0)
    
    # Diagonali superiori
    for k in range(1, u+1):
        diag = np.diag(A, k)
        O[u - k, k:] = diag
    
    # Diagonali inferiori
    for k in range(1, l+1):
        diag = np.diag(A, -k)
        O[u + k, :-k] = diag
    
    return O

# Esempio
n = 8
A = np.arange(1, n**2 + 1).reshape((n, n))
u, l = 1, 2

print('Input:\n', A)
print('Output:\n', es4_sol1(A, u, l))

Input:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
Output:
 [[ 0.  2. 11. 20. 29. 38. 47. 56.]
 [ 1. 10. 19. 28. 37. 46. 55. 64.]
 [ 9. 18. 27. 36. 45. 54. 63.  0.]
 [17. 26. 35. 44. 53. 62.  0.  0.]]


## Esercizio 5

Scrivere una functione che riceve in ingresso un vettore $c$ di $n$ componenti e restituisce in uscita una matrice $C$ di dimensioni $n\times n$ con la struttura circolante descritta nell'esempio seguente

Esempio ($n=4$)

$$\text{INPUT:} \begin{pmatrix}
c_1\\c_2\\c_3\\c_4
\end{pmatrix}\qquad\text{OUTPUT:}
\begin{pmatrix}
c_1&c_4&c_3&c_2\\
c_2&c_1&c_4&c_3\\
c_3&c_2&c_1&c_4\\
c_4&c_3&c_2&c_1
\end{pmatrix}
$$

In [252]:
# Soluzione senza cicli
def es5_sol1(c):
    n = c.size
    # Genera un array 2D con righe shiftate
    return np.column_stack([np.roll(c, i) for i in range(n)])

# Esempio
n = 4
c = np.arange(1, n+1)

print('Input:\n', c)
print('Output:\n', es5_sol1(c))

Input:
 [1 2 3 4]
Output:
 [[1 4 3 2]
 [2 1 4 3]
 [3 2 1 4]
 [4 3 2 1]]
